# Generated by Django 4.1.13 on 2025-01-06 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=250, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('customer_password', models.CharField(blank=True, max_length=250, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=500, null=True)),
                ('customer_payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
